"""initial schema baseline

Revision ID: 001_initial
Revises:
Create Date: 2026-03-23

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('account_snapshots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('financial_account_id', sa.Integer(), nullable=False),
        sa.Column('scraper_login_id', sa.Integer(), nullable=True),
        sa.Column('captured_at', sa.DateTime(), nullable=False),
        sa.Column('current_balance', sa.Float(), nullable=True),
        sa.Column('statement_balance', sa.Float(), nullable=True),
        sa.Column('minimum_payment', sa.Float(), nullable=True),
        sa.Column('due_date', sa.Text(), nullable=True),
        sa.Column('last_payment_amount', sa.Float(), nullable=True),
        sa.Column('last_payment_date', sa.Text(), nullable=True),
        sa.Column('credit_limit', sa.Float(), nullable=True),
        sa.Column('intro_apr_rate', sa.Float(), nullable=True),
        sa.Column('intro_apr_end_date', sa.Text(), nullable=True),
        sa.Column('regular_apr', sa.Float(), nullable=True),
        sa.Column('is_paid', sa.Boolean(), nullable=True),
        sa.Column('paid_date', sa.Text(), nullable=True),
        sa.Column('autopay_enabled', sa.Boolean(), nullable=True),
        sa.Column('is_paid_override', sa.Boolean(), nullable=True),
        sa.Column('is_paid_override_at', sa.DateTime(), nullable=True),
        sa.Column('raw_extracted_json', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
        sa.ForeignKeyConstraint(['scraper_login_id'], ['scraper_logins.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_statements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('financial_account_id', sa.Integer(), nullable=False),
        sa.Column('scraper_login_id', sa.Integer(), nullable=True),
        sa.Column('statement_month', sa.String(), nullable=False),
        sa.Column('statement_date', sa.String(), nullable=True),
        sa.Column('file_path', sa.Text(), nullable=True),
        sa.Column('file_size_bytes', sa.Integer(), nullable=True),
        sa.Column('downloaded_at', sa.DateTime(), nullable=True),
        sa.Column('intro_apr_rate', sa.Float(), nullable=True),
        sa.Column('intro_apr_end_date', sa.String(), nullable=True),
        sa.Column('regular_apr', sa.Float(), nullable=True),
        sa.Column('credit_limit', sa.Float(), nullable=True),
        sa.Column('raw_extracted_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
        sa.ForeignKeyConstraint(['scraper_login_id'], ['scraper_logins.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('financial_account_id', 'statement_month', name='uq_account_statement_month')
    )
    op.create_table('financial_account_identifiers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('financial_account_id', sa.Integer(), nullable=False),
        sa.Column('provider_key', sa.String(), nullable=False),
        sa.Column('identifier_type', sa.String(), nullable=False),
        sa.Column('identifier_value', sa.String(), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider_key', 'identifier_type', 'identifier_value', name='uq_account_identifier_value')
    )
    op.create_table('financial_account_login',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('financial_account_id', sa.Integer(), nullable=False),
        sa.Column('scraper_login_id', sa.Integer(), nullable=False),
        sa.Column('first_seen_at', sa.DateTime(), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(), nullable=False),
        sa.Column('last_success_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
        sa.ForeignKeyConstraint(['scraper_login_id'], ['scraper_logins.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('financial_account_id', 'scraper_login_id', name='uq_financial_account_login')
    )
    op.create_table('financial_account_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('balance_type', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('financial_accounts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('account_type_id', sa.Integer(), nullable=False),
        sa.Column('provider_key', sa.Text(), nullable=False),
        sa.Column('institution', sa.Text(), nullable=False),
        sa.Column('scraper_login_id', sa.Integer(), nullable=True),
        sa.Column('display_name', sa.Text(), nullable=True),
        sa.Column('account_number', sa.Text(), nullable=True),
        sa.Column('account_mask', sa.Text(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('first_seen_at', sa.DateTime(), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(), nullable=False),
        sa.Column('last_snapshot_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_type_id'], ['financial_account_types.id'], ),
        sa.ForeignKeyConstraint(['scraper_login_id'], ['scraper_logins.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider_key', 'account_number', name='uq_financial_account_provider_number')
    )
    op.create_table('import_candidates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('row_index', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('domain', sa.Text(), nullable=False),
        sa.Column('username', sa.Text(), nullable=False),
        sa.Column('password', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('match_confidence', sa.Float(), nullable=True),
        sa.Column('match_type', sa.Text(), nullable=True),
        sa.Column('provider_key', sa.Text(), nullable=True),
        sa.Column('label', sa.Text(), nullable=True),
        sa.Column('account_type', sa.Text(), nullable=True),
        sa.Column('is_new_provider', sa.Boolean(), nullable=False),
        sa.Column('is_duplicate', sa.Boolean(), nullable=False),
        sa.Column('existing_login_id', sa.Integer(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['existing_login_id'], ['scraper_logins.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('filename', sa.Text(), nullable=False),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('total_count', sa.Integer(), nullable=False),
        sa.Column('processed_count', sa.Integer(), nullable=False),
        sa.Column('high_confidence_count', sa.Integer(), nullable=False),
        sa.Column('needs_review_count', sa.Integer(), nullable=False),
        sa.Column('accepted_count', sa.Integer(), nullable=False),
        sa.Column('rejected_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_mappings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('domain_pattern', sa.Text(), nullable=False),
        sa.Column('provider_key', sa.Text(), nullable=False),
        sa.Column('label', sa.Text(), nullable=False),
        sa.Column('account_type', sa.Text(), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain_pattern')
    )
    op.create_table('promo_apr_periods',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('financial_account_id', sa.Integer(), nullable=False),
        sa.Column('promo_type', sa.String(), nullable=False),
        sa.Column('apr_rate', sa.Float(), nullable=False),
        sa.Column('regular_apr', sa.Float(), nullable=True),
        sa.Column('start_date', sa.String(), nullable=True),
        sa.Column('end_date', sa.String(), nullable=False),
        sa.Column('original_amount', sa.Float(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards_balances',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('rewards_program_id', sa.Integer(), nullable=False),
        sa.Column('captured_at', sa.DateTime(), nullable=False),
        sa.Column('balance', sa.Float(), nullable=False),
        sa.Column('monetary_value', sa.Float(), nullable=True),
        sa.Column('expiration_date', sa.String(), nullable=True),
        sa.Column('source_snapshot_id', sa.Integer(), nullable=True),
        sa.Column('raw_extracted_json', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['rewards_program_id'], ['rewards_programs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_snapshot_id'], ['account_snapshots.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards_programs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('financial_account_id', sa.Integer(), nullable=False),
        sa.Column('program_name', sa.String(), nullable=False),
        sa.Column('program_type', sa.String(), nullable=False),
        sa.Column('unit_name', sa.String(), nullable=True),
        sa.Column('cents_per_unit', sa.Float(), nullable=True),
        sa.Column('display_icon_url', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('financial_account_id', 'program_name', name='uq_rewards_program_account_name')
    )
    op.create_table('scraper_login_sync_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('scraper_login_id', sa.Integer(), nullable=False),
        sa.Column('provider_key', sa.String(), nullable=False),
        sa.Column('account_filter', sa.Text(), nullable=True),
        sa.Column('sync_type_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('accounts_found', sa.Integer(), nullable=True),
        sa.Column('snapshots_saved', sa.Integer(), nullable=True),
        sa.Column('agent_log_path', sa.Text(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['scraper_login_id'], ['scraper_logins.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sync_type_id'], ['sync_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraper_logins',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('provider_key', sa.String(), nullable=False),
        sa.Column('tool_key', sa.String(), nullable=False),
        sa.Column('institution', sa.String(), nullable=True),
        sa.Column('label', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('password_encrypted', sa.String(), nullable=True),
        sa.Column('login_url', sa.String(), nullable=True),
        sa.Column('account_type', sa.String(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('last_sync_started_at', sa.DateTime(), nullable=True),
        sa.Column('last_sync_finished_at', sa.DateTime(), nullable=True),
        sa.Column('last_sync_status', sa.String(), nullable=True),
        sa.Column('last_sync_error', sa.Text(), nullable=True),
        sa.Column('last_sync_account_count', sa.Integer(), nullable=True),
        sa.Column('last_sync_snapshot_count', sa.Integer(), nullable=True),
        sa.Column('last_auth_status', sa.String(), nullable=True),
        sa.Column('last_auth_at', sa.DateTime(), nullable=True),
        sa.Column('needs_full_sync', sa.Boolean(), nullable=False),
        sa.Column('last_full_sync_at', sa.DateTime(), nullable=True),
        sa.Column('last_balance_sync_at', sa.DateTime(), nullable=True),
        sa.Column('last_statements_sync_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key')
    )
    op.create_table('tool_run_outputs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tool_key', sa.String(), nullable=False),
        sa.Column('sync_run_id', sa.Integer(), nullable=True),
        sa.Column('scraper_login_id', sa.Integer(), nullable=True),
        sa.Column('provider_key', sa.String(), nullable=False),
        sa.Column('output_json', sa.JSON(), nullable=False),
        sa.Column('items_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['scraper_login_id'], ['scraper_logins.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['sync_run_id'], ['scraper_login_sync_runs.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_playbooks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('provider_key', sa.String(), nullable=False),
        sa.Column('extraction_prompt', sa.Text(), nullable=False),
        sa.Column('failed_actions', sa.JSON(), nullable=False),
        sa.Column('effective_patterns', sa.JSON(), nullable=False),
        sa.Column('navigation_tips', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider_key')
    )
    op.create_table('workflow_definitions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('prompt_template', sa.Text(), nullable=False),
        sa.Column('result_key', sa.String(), nullable=False),
        sa.Column('output_schema_json', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key')
    )
    op.create_table('workflow_revision_suggestions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tool_key', sa.String(), nullable=False),
        sa.Column('provider_key', sa.String(), nullable=False),
        sa.Column('sync_run_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('trigger_reason', sa.Text(), nullable=False),
        sa.Column('rationale', sa.Text(), nullable=False),
        sa.Column('suggested_definition_json', sa.JSON(), nullable=False),
        sa.Column('metrics_json', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['sync_run_id'], ['scraper_login_sync_runs.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    pass
